### PR TITLE
Fix socialsharing translations

### LINKED ISSUE #409: Fix lang resource not appearing on Transifex please
According existence of transifex config file in this project it seems, that there was attempt for adding this following instructions:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
But it seems, that this wasn't completed yet:
obrazek

Would it be possible to find (or cooperate with Nextcloud CI admins - as for example in this case https://github.com/nextcloud/docker-ci/issues/400 ) please?

Thanks :-)

### PR DESCRIPTION
**Pull request by nickvergessen**
Sync in https://github.com/nextcloud/socialsharing never worked in 6y.
Now it does

Fix #409

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]

File: translations-app/handleAppTranslations.sh [hunk 1]
```diff
@@ -11,6 +11,14 @@ gpg --list-keys
 # fetch git repo
 git clone git@github.com:$1/$2 /app
 
+# Migrate the transifex config to the new client version
```
Comment (nickvergessen) [inline translations-app/handleAppTranslations.sh:14]: Also worked https://github.com/nextcloud/serverinfo/commit/689b78e3175a6ace19611dcdc42314cfea3c27fc
